import { useState } from "react";
import { motion } from "framer-motion";
import Layout from "../../components/Layout";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "../../components/ui/tabs";
import { Card, CardContent, CardDescription, CardFooter, CardHeader, CardTitle } from "../../components/ui/card";
import { Button } from "../../components/ui/button";
import { Badge } from "../../components/ui/badge";
import { 
  AlertCircle, 
  Check, 
  ChevronDown, 
  Code, 
  FileText, 
  Image, 
  MessageSquare, 
  ShieldAlert, 
  Video,
  CheckCircle2,
  Server,
  Lock
} from "lucide-react";

export default function APIServices() {
  const [openFaq, setOpenFaq] = useState<number | null>(null);
  const [activeTab, setActiveTab] = useState("deepfake-detection");

  const toggleFaq = (index: number) => {
    setOpenFaq(openFaq === index ? null : index);
  };

  const apiServices = [
    {
      id: "deepfake-detection",
      title: "Deepfake Detection API",
      description: "Detect manipulated images and videos with our state-of-the-art deepfake detection algorithm.",
      icon: (isActive: boolean) => <ShieldAlert className={`h-6 w-6 ${isActive ? "text-white" : "text-primary"}`} />,
      status: "Coming Soon",
      features: [
        "Face manipulation detection",
        "Confidence scores and heatmaps",
        "Support for images and videos",
        "Detailed forensic analysis",
        "Fast processing times"
      ],
      useCases: [
        "Media verification",
        "Content moderation",
        "Social media platforms",
        "News organizations",
        "Digital forensics"
      ],
      details: [
        {
          title: "Input",
          content: "Images (JPG, PNG) or videos (MP4, MOV) containing human faces."
        },
        {
          title: "Output",
          content: "Detection results including manipulation probability, affected areas, confidence scores, and optional heatmap visualization."
        },
        {
          title: "Performance",
          content: "High accuracy with low false positive rates. Processing time depends on media complexity and server load."
        }
      ],
      techSpecs: {
        endpoints: ["/api/v1/deepfake/detect"],
        methods: ["POST"],
        requestFormat: "multipart/form-data or application/json with media URL",
        authentication: "API key required in request headers"
      }
    },
    {
      id: "ai-image-detection",
      title: "AI-Generated Image Detection API",
      description: "Identify AI-generated images created by models like DALL-E, Midjourney, and Stable Diffusion.",
      icon: (isActive: boolean) => <Image className={`h-6 w-6 ${isActive ? "text-white" : "text-primary"}`} />,
      status: "Coming Soon",
      features: [
        "Detection of multiple AI generation models",
        "Probability scores for generated content",
        "Artifact detection and analysis",
        "Support for various image formats",
        "Model-specific identification"
      ],
      useCases: [
        "Social media monitoring",
        "Authenticity verification",
        "Content moderation",
        "Academic research",
        "Digital rights management"
      ],
      details: [
        {
          title: "Input",
          content: "Images in common formats (JPG, PNG, WEBP)."
        },
        {
          title: "Output",
          content: "Detection results with probability score, identified generation model (when possible), and areas of interest."
        },
        {
          title: "Performance",
          content: "High accuracy for known models, with continuous updates to detect new AI generation techniques."
        }
      ],
      techSpecs: {
        endpoints: ["/api/v1/ai-generated/image/detect"],
        methods: ["POST"],
        requestFormat: "multipart/form-data or application/json with image URL",
        authentication: "API key required in request headers"
      }
    },
    {
      id: "ai-text-detection",
      title: "AI-Generated Text Detection API",
      description: "Identify text content generated by AI models like GPT-4, Claude, and other large language models.",
      icon: (isActive: boolean) => <MessageSquare className={`h-6 w-6 ${isActive ? "text-white" : "text-primary"}`} />,
      status: "Coming Soon",
      features: [
        "Detection across multiple AI text models",
        "Probability scoring system",
        "Language and style analysis",
        "Support for multiple languages",
        "Partial content analysis"
      ],
      useCases: [
        "Academic integrity",
        "Content authenticity",
        "Publishing verification",
        "Research validation",
        "Misinformation detection"
      ],
      details: [
        {
          title: "Input",
          content: "Plain text of any length (optimal results with 100+ words)."
        },
        {
          title: "Output",
          content: "Detection results with probability score, potential model identification, and statistical analysis."
        },
        {
          title: "Performance",
          content: "High accuracy for longer text samples, with improving performance for short texts."
        }
      ],
      techSpecs: {
        endpoints: ["/api/v1/ai-generated/text/detect"],
        methods: ["POST"],
        requestFormat: "application/json with text content",
        authentication: "API key required in request headers"
      }
    }
  ];

  const faqs = [
    {
      question: "How can I get access to the APIs?",
      answer: "Once the APIs are officially launched, you'll be able to register for an API key through our developer portal. All our API services are completely free for any use case."
    },
    {
      question: "What are the rate limits for the APIs?",
      answer: "Our API services are completely free with reasonable rate limits to ensure fair usage and system stability. For specific high-volume requirements, please contact our team."
    },
    {
      question: "How accurate are the detection algorithms?",
      answer: "Our detection models achieve high accuracy rates in controlled testing environments. However, accuracy may vary depending on content quality, generation techniques, and as new AI models emerge. We continuously update our detection algorithms to maintain high performance."
    },
    {
      question: "Will you provide SDKs for different programming languages?",
      answer: "Yes, we plan to provide official SDKs for Python, JavaScript/TypeScript, Java, and PHP. For other languages, detailed API documentation will be available to help developers build their own integrations."
    },
    {
      question: "Is my data secure when using the APIs?",
      answer: "Yes, we take data security seriously. All API requests are encrypted using HTTPS, and we don't store submitted content longer than necessary for processing. For specific compliance requirements, please contact our team."
    }
  ];

  return (
    <Layout>
      {/* Enhanced Header Section with Background - similar to detect.tsx */}
      <div className="relative">
        {/* Background with visible gradient */}
        <div className="absolute inset-0 z-0 overflow-hidden">
          <div className="w-full h-full bg-gradient-to-b from-primary/60 via-primary/40 to-background"></div>
          <div className="absolute top-0 right-0 w-72 h-72 bg-primary/30 rounded-full blur-3xl transform -translate-y-1/3"></div>
          <div className="absolute mb-10 bottom-1/4 left-0 w-64 h-64 bg-primary/25 rounded-full blur-3xl transform translate-y-1/4"></div>
        </div>
        
        {/* Header Content */}
        <div className="relative z-10 pt-16 pb-16 px-4 sm:px-6 lg:px-8 max-w-[1400px] mx-auto">
          <motion.div 
            className="text-center max-w-4xl mx-auto"
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.7 }}
          >
            <div className="inline-flex items-center justify-center mb-6 relative">
              <div className="absolute inset-0 bg-primary/20 rounded-full blur-md"></div>
              <span className="relative inline-flex items-center px-4 py-2 rounded-full bg-black/80 border border-primary/30 text-white text-sm font-medium">
                <Code className="h-4 w-4 mr-2" />
                Developer Resources
              </span>
            </div>
            
            <h1 className="text-3xl md:text-4xl lg:text-5xl font-bold mb-6 leading-tight tracking-tight">
              Powerful <span className="gradient-text">Detection APIs</span> for Developers
            </h1>
            
            <p className="text-muted-foreground max-w-2xl mx-auto text-base md:text-lg mb-8 leading-relaxed">
              Integrate advanced deepfake and AI-generated content detection directly into your 
              applications with our powerful and easy-to-use APIs
            </p>

            <div className="flex flex-wrap gap-4 justify-center items-center text-sm text-black/80 dark:text-white/90 mb-4">
              <div className="flex items-center gap-2 px-3 py-1.5 bg-primary/10 rounded-full border border-primary/70">
                <CheckCircle2 className="h-4 w-4 text-primary" /> 
                <span>3 Detection Services</span>
              </div>
              <div className="flex items-center gap-2 px-3 py-1.5 bg-primary/10 rounded-full border border-primary/70">
                <Server className="h-4 w-4 text-primary" /> 
                <span>Fast & Scalable</span>
              </div>
              <div className="flex items-center gap-2 px-3 py-1.5 bg-primary/10 rounded-full border border-primary/70">
                <Lock className="h-4 w-4 text-primary" /> 
                <span>Secure Implementation</span>
              </div>
            </div>
          </motion.div>
        </div>
      </div>

      <motion.div 
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.5 }}
        className="container mx-auto px-4 py-8"
      >
        {/* Tabs for API Services */}
        <Tabs 
          defaultValue={apiServices[0].id} 
          className="mb-12 w-full"
          onValueChange={(value) => setActiveTab(value)}
          value={activeTab}
        >
          <TabsList className="w-full flex justify-between mb-8 p-1 gap-2">
            {apiServices.map((service, index) => (
              <TabsTrigger 
                key={service.id} 
                value={service.id}
                className="flex-1 flex items-center justify-center gap-2 py-3 px-4"
              >
                {service.icon(activeTab === service.id)}
                <span>{service.title}</span>
              </TabsTrigger>
            ))}
          </TabsList>

          {apiServices.map((service, index) => (
            <TabsContent 
              key={service.id} 
              value={service.id}
              className="animate-in fade-in-50 duration-500"
            >
              <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
                <div className="lg:col-span-2 space-y-6">
                  <Card>
                    <CardHeader>
                      <div className="flex items-center gap-3 mb-2">
                        {service.icon(false)}
                        <Badge variant="outline">{service.status}</Badge>
                      </div>
                      <CardTitle className="text-2xl">{service.title}</CardTitle>
                      <CardDescription className="text-base">{service.description}</CardDescription>
                    </CardHeader>
                    <CardContent className="space-y-4">
                      <h3 className="text-lg font-medium">Key Features</h3>
                      <ul className="grid grid-cols-1 md:grid-cols-2 gap-2">
                        {service.features.map((feature, i) => (
                          <li key={i} className="flex items-center gap-2">
                            <Check className="h-4 w-4 text-green-500" />
                            <span>{feature}</span>
                          </li>
                        ))}
                      </ul>

                      <h3 className="text-lg font-medium pt-4">Technical Details</h3>
                      <div className="space-y-4">
                        {service.details.map((detail, i) => (
                          <div key={i} className="border-b pb-3 last:border-0">
                            <h4 className="font-medium text-primary">{detail.title}</h4>
                            <p className="text-muted-foreground">{detail.content}</p>
                          </div>
                        ))}
                      </div>

                      <h3 className="text-lg font-medium pt-4">API Specification</h3>
                      <div className="bg-muted p-4 rounded-md font-mono text-sm space-y-2">
                        <div className="flex flex-col md:flex-row md:items-center gap-2 md:gap-8">
                          <span className="font-medium">Endpoints:</span>
                          <span>{service.techSpecs.endpoints.join(", ")}</span>
                        </div>
                        <div className="flex flex-col md:flex-row md:items-center gap-2 md:gap-8">
                          <span className="font-medium">Methods:</span>
                          <span>{service.techSpecs.methods.join(", ")}</span>
                        </div>
                        <div className="flex flex-col md:flex-row md:items-center gap-2 md:gap-8">
                          <span className="font-medium">Format:</span>
                          <span>{service.techSpecs.requestFormat}</span>
                        </div>
                        <div className="flex flex-col md:flex-row md:items-center gap-2 md:gap-8">
                          <span className="font-medium">Auth:</span>
                          <span>{service.techSpecs.authentication}</span>
                        </div>
                      </div>
                    </CardContent>
                    <CardFooter>
                      <Button className="w-full md:w-auto" disabled>
                        Documentation Coming Soon
                      </Button>
                    </CardFooter>
                  </Card>
                </div>

                <div className="lg:col-span-1 space-y-6">
                  <Card>
                    <CardHeader>
                      <CardTitle className="text-xl">Use Cases</CardTitle>
                      <CardDescription>
                        Common applications for the {service.title}
                      </CardDescription>
                    </CardHeader>
                    <CardContent>
                      <ul className="space-y-3">
                        {service.useCases.map((useCase, i) => (
                          <li key={i} className="flex items-start gap-2">
                            <div className="h-6 w-6 rounded-full bg-primary/10 flex items-center justify-center text-primary mt-0.5">
                              {i + 1}
                            </div>
                            <span>{useCase}</span>
                          </li>
                        ))}
                      </ul>
                    </CardContent>
                  </Card>

                  <Card>
                    <CardHeader>
                      <CardTitle className="text-xl">Service Information</CardTitle>
                      <CardDescription>
                        Free access for all users
                      </CardDescription>
                    </CardHeader>
                    <CardContent>
                      <div className="space-y-4">
                        <div className="flex items-center gap-2">
                          <Check className="h-5 w-5 text-green-500" />
                          <span>Completely free to use</span>
                        </div>
                        <div className="flex items-center gap-2">
                          <Check className="h-5 w-5 text-green-500" />
                          <span>No credit card required</span>
                        </div>
                        <div className="flex items-center gap-2">
                          <Check className="h-5 w-5 text-green-500" />
                          <span>Simple API key registration</span>
                        </div>
                        <div className="flex items-center gap-2">
                          <Check className="h-5 w-5 text-green-500" />
                          <span>Reasonable rate limits</span>
                        </div>
                      </div>
                    </CardContent>
                  </Card>
                </div>
              </div>
            </TabsContent>
          ))}
        </Tabs>

        {/* Integrations Section */}
        <div className="mb-16">
          <h2 className="text-2xl font-bold mb-6 text-center">Integration Examples</h2>
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
            <Card>
              <CardHeader>
                <CardTitle className="flex items-center gap-2">
                  <FileText className="h-5 w-5" />
                  <span>Code Example</span>
                </CardTitle>
              </CardHeader>
              <CardContent>
                <div className="bg-muted p-4 rounded-md font-mono text-sm overflow-x-auto">
                  <pre className="text-xs whitespace-pre-wrap break-all sm:break-normal">
{`// JavaScript/Node.js Example
const fetchDetectionResults = async (imageUrl) => {
  const response = await fetch(
    'https://api.deepmediainspection.com/v1/deepfake/detect',
    {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'Authorization': 'Bearer YOUR_API_KEY',
      },
      body: JSON.stringify({
        url: imageUrl,
        returnHeatmap: true
      }),
    }
  );
  
  return await response.json();
};`}
                  </pre>
                </div>
              </CardContent>
            </Card>

            <Card>
              <CardHeader>
                <CardTitle className="flex items-center gap-2">
                  <FileText className="h-5 w-5" />
                  <span>Response Format</span>
                </CardTitle>
              </CardHeader>
              <CardContent>
                <div className="bg-muted p-4 rounded-md font-mono text-sm overflow-x-auto">
                  <pre className="text-xs whitespace-pre-wrap break-all sm:break-normal">
{`{
  "status": "success",
  "data": {
    "isManipulated": true,
    "confidenceScore": 0.93,
    "detectionMethod": "deep-learning",
    "analyzedAreas": [
      {
        "region": "face",
        "confidence": 0.96,
        "boundingBox": [120, 80, 200, 200]
      }
    ],
    "heatmapUrl": "https://api.example.com/results/hm_12345.jpg",
    "processingTimeMs": 1240
  }
}`}
                  </pre>
                </div>
              </CardContent>
            </Card>

            <Card>
              <CardHeader>
                <CardTitle className="flex items-center gap-2">
                  <AlertCircle className="h-5 w-5" />
                  <span>Important Notes</span>
                </CardTitle>
              </CardHeader>
              <CardContent className="space-y-3">
                <div className="flex items-start gap-2">
                  <div className="h-6 w-6 rounded-full bg-amber-500/10 flex items-center justify-center text-amber-500 mt-0.5">
                    <AlertCircle className="h-4 w-4" />
                  </div>
                  <span>API keys should never be exposed in client-side code</span>
                </div>
                <div className="flex items-start gap-2">
                  <div className="h-6 w-6 rounded-full bg-amber-500/10 flex items-center justify-center text-amber-500 mt-0.5">
                    <AlertCircle className="h-4 w-4" />
                  </div>
                  <span>Results may vary based on content quality</span>
                </div>
                <div className="flex items-start gap-2">
                  <div className="h-6 w-6 rounded-full bg-amber-500/10 flex items-center justify-center text-amber-500 mt-0.5">
                    <AlertCircle className="h-4 w-4" />
                  </div>
                  <span>Webhook notifications will be available for asynchronous processing</span>
                </div>
              </CardContent>
            </Card>
          </div>
        </div>

        {/* FAQs */}
        <div className="mb-16">
          <h2 className="text-2xl font-bold mb-6 text-center">Frequently Asked Questions</h2>
          <div className="space-y-4 max-w-3xl mx-auto">
            {faqs.map((faq, index) => (
              <div 
                key={index} 
                className="border rounded-lg overflow-hidden"
              >
                <button
                  className="flex items-center justify-between w-full p-4 text-left font-medium"
                  onClick={() => toggleFaq(index)}
                >
                  {faq.question}
                  <ChevronDown 
                    className={`h-5 w-5 transition-transform duration-200 ${
                      openFaq === index ? "transform rotate-180" : ""
                    }`} 
                  />
                </button>
                {openFaq === index && (
                  <div className="p-4 pt-0 text-muted-foreground">
                    {faq.answer}
                  </div>
                )}
              </div>
            ))}
          </div>
        </div>

        {/* Call to Action */}
        <div className="text-center">
          <h2 className="text-2xl font-bold mb-4">Ready to Get Started?</h2>
          <p className="text-muted-foreground max-w-2xl mx-auto mb-6">
            Join our waitlist to be notified when our API services launch. All services are completely free to use for any purpose.
          </p>
          <Button size="lg" disabled>
            Sign Up for Early Access
          </Button>
        </div>
      </motion.div>
    </Layout>
  );
} 